JuliaSymbolics/Symbolics.jl

README.md
It's a starting point and it'll get some changes.
=> Throw together a README

docs/src/manual/derivatives.md, src/Symbolics.jl, test/diff.jl
This clashes with a ton of things so it's not a good idea.
=> do not export derivative functions

src/equations.jl
In response to request in #103, it was suggested that we update the docs to show Broadcasted usage instead of introducing a change that may need to be broken in the future.
This PR adds 2 examples to that effect.
=> Update docs to reflect changes proposed in #103

README.md, docs/src/tutorials/symbolic_functions.md
Three words added to description of `build_function` in tutorial.
Rest of changes are spaces in code, that can make code more readable.
=> Changes in documentation for better readability

docs/src/tutorials/symbolic_functions.md
Mostly adding spaces in code for better readability, some spaces removed whe they are unnecessary. In one places in plain text added code stale for symbols of variables.
=> Aesthetically changes in tutorial

src/diff.jl, src/utils.jl, test/build_function.jl, test/diff.jl
=> New `Derivative -> single term` lowering

docs/src/tutorials/symbolic_functions.md
This might not be the best wording or placement, but I think it should be somewhere.
=> add `D.x` to derivatives tutorial

src/num.jl, test/overloads.jl
Fix https://github.com/JuliaSymbolics/Symbolics.jl/issues/139
=> Fix iszero(Num(0.0))

README.md, docs/src/tutorials/auto_parallel.md, docs/src/tutorials/symbolic_functions.md
In commits I wrote where there are errors in code in tutorial. I also proposed two changes to tutorial, explanations are in commits.
Plus few aesthetically changes.
=> Errors and propositions for tutorial

README.md, docs/src/tutorials/auto_parallel.md, docs/src/tutorials/symbolic_functions.md
Few errors in tutorial removed, added some text to this on generating functions in C. I hope that this can be helpful.
=> Corrections and changes in tutorials

src/build_function.jl
Fix https://github.com/JuliaSymbolics/Symbolics.jl/issues/155
=> Speed up unflatten_long_ops by avoiding repeated re-sorting

src/diff.jl, src/extra_functions.jl, test/diff.jl
=> handle ifelse explicitly to avoid domain errors

src/extra_functions.jl, test/overloads.jl
=> Fix sign(Num(1))

src/register.jl
Just a couple of minor adjustments.
=> Fix typos in src/register.jl

src/num.jl, test/overloads.jl
=> Overload boolean operations

src/extra_functions.jl
Fixes https://github.com/JuliaSymbolics/Symbolics.jl/issues/251
=> Register floor and ceil

src/latexify_recipes.jl, test/latexify.jl, test/latexify_refs/frac1.txt
=> Fix _toexpr for `Mul`

Project.toml
Reverts JuliaSymbolics/Symbolics.jl#271
=> Revert "CompatHelper: bump compat for "SymbolicUtils" to "0.13""

Project.toml, src/num.jl
fix up for https://github.com/JuliaSymbolics/SymbolicUtils.jl/pull/271
=> Update for polynomial change in SU

src/diff.jl, test/diff.jl
Adds the feature needed in https://discourse.julialang.org/t/chain-rule-in-symbolics-jl/63146
=> Apply chain rule on symbolic functions

README.md
Added syntax highlighting for bibtex entry and made some formatting changes in README.
=> Formatting changes in `README`

src/variable.jl
=> update variable macro docs for array variables

src/build_function.jl
and revert bug introduced in #255
=> Update `buildvarnnumbercache` to actually handle non array types

src/arrays.jl, src/diff.jl, src/equations.jl, src/num.jl, test/arrays.jl
Fix https://github.com/SciML/ModelingToolkit.jl/issues/1109
This PR needs https://github.com/JuliaSymbolics/SymbolicUtils.jl/pull/308
=> Implicitly broadcast D and ~

src/Symbolics.jl
now that there is a readme example
=> module docstring

docs/src/tutorials/converting_to_C.md
=> You can't assign to du itself

src/linear_algebra.jl
Fix https://github.com/JuliaSymbolics/Symbolics.jl/issues/357
=> Use the one-arg checknonsingular

src/diff.jl, test/diff.jl
* drop-in replacement for the corresponding interface in SparsityDetection.jl
=> Add jacobian_sparsity for mutating functions of Arrays of concrete types

docs/src/tutorials/symbolic_functions.md
Moved "building functions" and "building non-allocating parallel functions for sparse matrices" to the end of the tutorial.
=> Rearrange "symbolic functions" tutorial

src/build_function.jl, test/build_function.jl
Fix https://github.com/JuliaSymbolics/Symbolics.jl/issues/383
=> Fix skipzeros

src/equations.jl, test/diff.jl
sorry lol
i also changed the other dispatch from vector to array.
tests passed locally
=> fix substitute on array{num}

src/difference.jl, test/difference.jl
=> define `^` for difference

Project.toml, src/Symbolics.jl, src/semipoly.jl, test/runtests.jl, test/semipoly.jl
This adds
- `semilinear_form(exprs::Vector, vars::Vector)` which returns `A` and `c` such that `exprs == A * vars + c`
- `semipolynomial_form(exprs::Vector, vars::Vector, degree)` which returns a vector of dictionaries of coefficients of polynomial terms up to `degree` and a vector of nonlinear terms.
Needs tests and docs.
=> Semi-polynomial form

src/arrays.jl
=> Remove pirate `ndims` method

src/arrays.jl, src/utils.jl, test/arrays.jl
=> solve some bugs with get_variables on array variables

src/array-lib.jl, src/arrays.jl, test/arrays.jl
=> fix extruded dim in broadcast when all args have size 1

src/diff.jl, src/difference.jl, test/difference.jl
This supersedes #453 
The intention is to introduce additional operators
`Sample, Hold, Shift` in ModelingToolkit.
=> abstract type Operator

docs/src/tutorials/auto_parallel.md
Fixes https://github.com/JuliaSymbolics/Symbolics.jl/issues/467
=> Fix auto-parallel tutorial

docs/src/tutorials/symbolic_functions.md
=> Corrected the output from f(u[1:4])

src/register.jl, test/macro.jl
=> Fix register fallback

test/diff.jl
found here https://github.com/JuliaSymbolics/SymbolicUtils.jl/runs/4815884565?check_suite_focus=true
=> update test to pass with new rules in SU

src/linear_algebra.jl
Fix https://github.com/JuliaSymbolics/Symbolics.jl/issues/500
=> Fix the ambiguity of sparse

src/utils.jl, test/diff.jl
I'm not familiar with the code, so please review.
This should fix https://github.com/SciML/ModelingToolkit.jl/issues/1240 and https://github.com/SciML/ModelingToolkit.jl/issues/1283 when the patch reaches ModelingToolkit.
┆Issue is synchronized with this [Trello card](https://trello.com/c/GwcQzB6v) by [Unito](https://www.unito.io)
=> diff2term: handle elements of symbolic arrays

src/arrays.jl, test/arrays.jl
Solution to #483
┆Issue is synchronized with this [Trello card](https://trello.com/c/8bW3q75X) by [Unito](https://www.unito.io)
=> fix nested scalarize

src/diff.jl, test/diff.jl
=> Don't throw array derivative error in an innocent case

src/wrapper-types.jl, test/macro.jl
Fix for https://github.com/JuliaSymbolics/SymbolicUtils.jl/issues/402#issuecomment-1074261734
┆Issue is synchronized with this [Trello card](https://trello.com/c/57aUT0Rw) by [Unito](https://www.unito.io)
=> fix is_wrapper_type when subtype

src/build_function.jl, test/build_function.jl
=> Fix SparseMatrixCSC codegen when ShardedForm is used.

src/latexify_recipes.jl
Latexify doesn't support align with no equal sign, so equations with connections will look a bit worse.
=> Fix latexify for Connection

src/diff.jl, test/diff.jl
=> fix bug in occursin_info

src/diff.jl
Here is a proposal of a simple example using the function
=> add example to expand_derivatives

src/latexify_recipes.jl
=> Add show method for latexify / equation type

Project.toml, src/arrays.jl, src/diff.jl, src/utils.jl, src/variable.jl, test/arrays.jl, test/diff.jl, test/macro.jl, test/overloads.jl
=> Revert revert dependent array convention

src/array-lib.jl, test/build_function.jl
=> handle refs in broadcast

src/semipoly.jl, test/semipoly.jl
=> Fix semilinear_form with 1-arg nonlinear term times the variable

src/arrays.jl, test/arrays.jl
=> fix scalarize for inv

src/arrays.jl
should fix downstream CI and #670
=> Fix wrapping in scalarize, fix metadata propagation

src/semipoly.jl, test/semipoly.jl
=> WIP: constants as 0 degree monomials in semipolynomial form

src/array-lib.jl, src/arrays.jl, test/arrays.jl
Fix https://github.com/SciML/ModelingToolkit.jl/issues/1736
=> RefValue handling in symtype inference

src/build_function.jl
=> make kwarg slurping the same across Julia target methods

src/diff.jl
This is a suggestion of an intermediary function in `sparsejacobian`, but that can be useful on its own.
Please, let me know what you think of this suggestion.
=> Add `sparsejacobian_vals` function

src/variable.jl, test/arrays.jl
Fix https://github.com/SciML/ModelingToolkit.jl/issues/1854
=> Handle getname edge case

src/diff.jl, test/diff.jl
resolve https://github.com/JuliaSymbolics/Symbolics.jl/pull/759#discussion_r990799312
=> Update docstring `jacobian_sparsity` and `hessian_sparsity`

test/runtests.jl
This file did not seem to be used anywhere.
=> include more test files

docs/src/manual/expression_manipulation.md
Inside the documentation for Symbolics.jl, I put in a link to "rewriter", so one knows how to use a custom rewriter.
=> Included a link to rewriter documentation in Symbolics.jl

docs/make.jl, docs/src/manual/parsing.md, src/Symbolics.jl, src/parsing.jl, test/parsing.jl, test/runtests.jl
With known and documented limitations
=> Add a function to parse Julia expressions into symbolic expressions

src/latexify_recipes.jl, test/latexify_refs/derivative1.txt, test/latexify_refs/derivative2.txt, test/latexify_refs/derivative3.txt, test/latexify_refs/derivative4.txt, test/latexify_refs/derivative5.txt, test/latexify_refs/equation2.txt, test/latexify_refs/equation_vec2.txt
=> fix latex printing for derivatives

src/array-lib.jl, test/arrays.jl
=> Fix `getindex` dropping `metadata`

docs/src/manual/expression_manipulation.md, src/utils.jl
Following https://github.com/JuliaSymbolics/Symbolics.jl/pull/677.
=> docs: add `degree` and `coeff`

src/diff.jl, src/linear_algebra.jl
Corrects some typos in the repository.
=> Correct some typos

src/latexify_recipes.jl, test/latexify.jl, test/latexify_refs/integral1.txt, test/latexify_refs/integral2.txt
I added a special case to `latexify_derivative` and `_toexpr` in `src/latexify_recipes.jl` to latexify integrals
=> Latexify integral

Project.toml, src/linear_algebra.jl, test/arrays.jl
Fixes inverse for 1x1 matrix (Issue #895). I also noticed that I made it impossible to choose the method of inverse, so I fixed this as well.
=> Fixes #895

src/build_function.jl
This corrects a very minor bug:
The function `build_function` accepts the keyword `conv` to perform the conversion function of symbolic types to Expr. However, this was never implemented and `toexpr` was "hard-wired". This PR fixes this.
=> Fixed minor bug in src/build_function where the keyword conv was not used

Project.toml, src/groebner_basis.jl
=> Fix warning caused by DynamicPolynomials load

Project.toml, ext/SymbolicsPreallocationToolsExt.jl, test/nested_forwarddiff_sparsity.jl
Quick merge for hotfix, tested locally.
=> Fix PreallocationTools extension swap

src/struct.jl
https://github.com/JuliaSymbolics/Symbolics.jl/pull/1091#discussion_r1525004229
=> fix: rm duplicated method

Project.toml
=> revert SU lowerbound

src/rewrite-helpers.jl
Reverts JuliaSymbolics/Symbolics.jl#1158
=> Revert "Rewrite deprecation warnings"

src/utils.jl
=> Fix opname

test/latexify_refs/equation_vec1.txt, test/latexify_refs/equation_vec2.txt
Like https://github.com/SciML/ModelingToolkit.jl/pull/2942
=> Fix Latex tests to use new upstream equation equality aligning 

Project.toml, ext/SymbolicsPreallocationToolsExt.jl
=> Make SymbolicsPreallocationTools also depend on ForwardDiff

src/num.jl
=> Remove stack-overflowy `convert` method

docs/src/manual/expression_manipulation.md
Documentation follow-up to https://github.com/JuliaSymbolics/Symbolics.jl/pull/1445.
=> Document factors(), terms(), numerator() and denominator()

test/arrays.jl
Changes a name that the typos spell checker is complaining about.
=> Fix typos check

src/diff.jl, test/diff.jl
Fixes https://github.com/JuliaSymbolics/Symbolics.jl/issues/1383 with @willrae42's solution.
=> Expand derivatives of array variables

src/variable.jl, test/macro.jl
Close https://github.com/SciML/ModelingToolkit.jl/issues/3356
=> fix: unwrap symbolic metadata

Project.toml, src/arrays.jl, src/build_function.jl, test/build_function_tests/intermediate-exprs-inplace.jl, test/build_function_tests/intermediate-exprs-outplace.jl, test/build_function_tests/manual-limits-inplace.jl, test/build_function_tests/manual-limits-outplace.jl, test/build_function_tests/stencil-broadcast-inplace.jl, test/build_function_tests/stencil-broadcast-outplace.jl, test/build_function_tests/stencil-extents-inplace.jl, test/build_function_tests/stencil-extents-outplace.jl, test/build_function_tests/stencil-transpose-arrayop-inplace.jl, test/build_function_tests/stencil-transpose-arrayop-outplace.jl, test/build_function_tests/transpose-inplace.jl, test/build_function_tests/transpose-outplace.jl, test/build_function_tests/transpose-term-inplace.jl
=> build: lower bound SymbolicUtils

src/arrays.jl, src/build_function.jl, src/variable.jl, test/build_function.jl, test/build_function_tests/intermediate-exprs-inplace.jl, test/build_function_tests/intermediate-exprs-outplace.jl, test/build_function_tests/manual-limits-outplace.jl, test/build_function_tests/stencil-broadcast-outplace.jl, test/build_function_tests/stencil-extents-outplace.jl, test/build_function_tests/stencil-transpose-arrayop-outplace.jl, test/build_function_tests/transpose-outplace.jl
RGFs don't like `args...` and we didn't test `iip_config` with RGFs.
=> fix: fix `iip_config` with RGF

.github/workflows/Downstream.yml, Project.toml, src/diff.jl
Requires https://github.com/JuliaSymbolics/SymbolicUtils.jl/pull/727
=> refactor: performance improvements for `expand_derivatives`

src/diff.jl, test/diff.jl
Fixes https://github.com/JuliaSymbolics/Symbolics.jl/issues/1535
=> Fix and better test derivatives w.r.t. array variables

docs/src/manual/structs.md, src/struct.jl
@ChrisRackauckas the machinery for #1541 is already in there, so just adding a doc page for it
=> docs: add documentation for symbolic structs

src/linear_algebra.jl, test/linear_solver.jl
Checks if there's division by 0, and sets output to NaN if so. Address issue #1540
=> Set dividing by 0 to NaN

docs/src/manual/integration.md
I fixed the markdown display of the table in docs/src/manual/integration.md.
=> Fix integration.md

src/utils.jl, test/coeff.jl
=> fix: fix `coeff` for symbolic coefficients
