JuliaSymbolics/Symbolics.jl

- docs/src/manual/functions.md
Chris Rackauckas suggested that "parameters" macro doesn't exist for Symbolics; that it is a ModelingToolkit concept. So I assume that one can move statements in parameters macros into variables macros?? The same problem is found several other places in the documentation.
> "Parameters" macro isn't defined for Symbolics?

- src/latexify_recipes.jl
Extension of https://github.com/SciML/ModelingToolkit.jl/pull/726. Ref: https://github.com/JuliaSymbolics/Symbolics.jl/issues/41
With this PR, any `AbstractArray{Num}` will automatically latexified (if possible).
(This is the default for SymPy as well.)
> Automatically latexify AbstractArray{Num}

- src/build_function.jl
Restores the BCR benchmark in https://github.com/SciML/ModelingToolkit.jl/issues/553
> call unflatten_long_ops in _set_array

- src/num.jl
- test/diff.jl
Fixes https://github.com/JuliaSymbolics/SymbolicUtils.jl/issues/223
We were accidentally rewriting stuff into `Num`s which was causing all sorts of mayhem because `Num <: Number`.
> Unwrap `Num` values in substitute

- src/extra_functions.jl
Specializes on Num <: Number so it will be something to make note of with array symbolics
> Handle norm(::Num)

- src/build_function.jl
- test/build_targets.jl
Consistent function signature for C code generated by build_function (plus valid code in more cases),  fixes #106
> Improve build_function for CTarget()

- src/build_function.jl
- test/build_function.jl
Fix https://github.com/SciML/ModelingToolkit.jl/issues/800
> Fix set_array for sparse arrays

- src/equations.jl
- test/overloads.jl
This is a retake of https://github.com/SciML/ModelingToolkit.jl/pull/795 based on an idea by @YingboMa that an equation of complex numbers should return a list of two equations for the real and imaginary part.
I've added some code such that if the concrete type inside the `Num` on neither side is symbolic, no equation is generated for that. This prevents code like `im*a ~ im*b` from generating `0 ~ 0` for the real part. Currently there is no safeguard against writing `1*im ~ 2*im` which will simply generate no equations at all.
On my end `@test real(a) === a` is broken, but this is not due to anything I did.
> Support complex equations

- src/build_function.jl
- test/build_function.jl
- test/build_targets.jl
Closes #119 
Feel free to close / not merge. This behavior makes sense to me, but I'm not sure what behavior y'all want for `build_function(...; target=CTarget())` calls. 
This PR designates all function inputs (every function argument that is __not__ the first "output" argument) as `const` in generated C functions. To my knowledge, this already matches `build_function` behavior, since function inputs are not modified in any generated `build_function` code. 
Tests should pass. I just rebased this over the latest `master` branch.
> CTarget inputs defined as const

- src/num.jl
- test/overloads.jl
There were overloads for dividing two complex numbers, but not for a number and a complex.
Now there are.
> Add complex overloads for division

- src/latexify_recipes.jl
- test/latexify.jl
Previously, calling `latexify(n::Num)` would just call `string(n)` because `Num <: Real`. Now, `latexify(n::Num)` creates an expression from `value(n)`, and then `latexify`'s that.
The calls to `Symbol` are necessary because `Latexify` expects an operation represented as a symbol, and not the actual function type (`typeof(*)` vs `:*` for example).
Fixes #109. Fixes #135.
> Fix `latexify` for `Num`

- src/variable.jl
First part of https://github.com/SciML/ModelingToolkit.jl/issues/881
> allow transforming the Sym object in _parse_vars (`@variables`)

- Project.toml
We don't test them, and other dependencies will not be updating them.
> Ignore earlier Julia's before v1.5

- src/build_function.jl
In `build_function` for non-julia targets, symbolic variables in expressions are replaced by references to the corresponding element of the input arrays. To find the right index, input arrays were searched linearly for the right symbolic variable for each replacement. Now we first (and only once) build a dictionary for symbolic variable -> index lookup. This speeds up `build_function` for expressions with large numbers of variables.
> More efficient expression building for non-julia targets

- src/latexify_recipes.jl
- test/latexify.jl
- test/runtests.jl
Currently a negative variable `-x` is rendered as `-1*x` in latex. Changing it to `-x` is more natural looking.
> to render -1*x as -x in latex

- Project.toml
- src/build_function.jl
Hi there, this PR implements the changes from https://github.com/JuliaSymbolics/SymbolicUtils.jl/pull/265 in `Symbolics.jl` to solve #177.
I'm not sure what has to be done on the dependencies management side though, so this **change might break `master`**.
> Update _build_function to use inbounds keyword of DestructuredArgs

- src/latexify_recipes.jl
- test/latexify.jl
This PR makes `_toexpr` produce expressions with fractions in then, which in turn makes `latexify` output fractions. I subjectively think that this looks a lot nicer in Jupyter.
The PR also includes several cleanup/reorganization commits. I've done my best to keep the commits self contained, so it is probably easiest to review one commit at a time. I can remove them if you would rather not review such a large change, want to keep `git blame` useful, etc.
> Latexify fractions

- docs/src/manual/sparsity_detection.md
- src/diff.jl
- src/linear_algebra.jl
- src/linearity.jl
- test/islinear_affine.jl
- test/runtests.jl
Fixes:
```julia
using ModelingToolkit
@parameters t p
@variables x(t)
D = Differential(t)
eqs = [D(x) ~ x]
sys = ODESystem(eqs,t)
ModelingToolkit.islinear(sys) # true
eqs = [D(x) ~ p]
sys = ODESystem(eqs,t)
ModelingToolkit.islinear(sys) # false
```
> Distinguish linear from affine and fix linearity checks on single sym

- src/num.jl
- test/overloads.jl
This is just a copy of the above `iszero` implementation. Without this `_isone` on complex numbers will not work correctly because one `isone` on complex numbers checks `iszero` and `isone` on the real and imaginary parts, one of which currently return false, while the other returns a Num containing the boolean expression.
> add isone(::Num)

- src/variable.jl
Closes #133. With this PR:
```julia
julia> using Symbolics; @variables x[-3:3]
[ Info: Precompiling Symbolics [0c5d862f-8b57-4792-8d23-62f2024744c7]
1-element Vector{Vector{Num}}:
[x₋₃, x₋₂, x₋₁, x₀, x₁, x₂, x₃]
```
> Add support for negative index

- src/build_function.jl
- test/build_function.jl
Fixes https://discourse.julialang.org/t/function-compiles-every-time/63273/5 by giving the arguments unique names. MWE:
```julia
using ModelingToolkit, OrdinaryDiffEq
@variables t x(t) RHS(t)  # independent and dependent variables
@parameters τ       # parameters
D = Differential(t) # define an operator for the differentiation w.r.t. time
@named fol_separate = ODESystem([ RHS  ~ (1 - x)/τ,
D(x) ~ RHS ])
sys = structural_simplify(fol_separate)
@time begin
prob = ODEProblem(sys, [x => 0.0], (0.0,10.0), [τ => 3.0])
sol = solve(prob, Tsit5())
end
```
```
0.001047 seconds (2.20 k allocations: 126.812 KiB)
0.001023 seconds (2.20 k allocations: 126.812 KiB)
0.001021 seconds (2.20 k allocations: 125.672 KiB)
0.001045 seconds (2.20 k allocations: 125.672 KiB)
```
while it used to be 99.9% compile …
> Unique function argument names for no recompilation

- src/utils.jl
- test/overloads.jl
Should resolve the issue of collecting variables created by indexing a symbolic array:
Before
```julia
@variables x[1:3] y z(t)
ex = x[1] + y + sin(z)
Symbolics.get_variables(ex) # Returns x, y, z(t) 
``` 
After:
```julia
@variables x[1:3] y z(t)
ex = x[1] + y + sin(z)
Symbolics.get_variables(ex) # Returns  x[1], y, z(t)
``` 
Tbh, maybe there is a more elegant dispatch I've not come up wth :smile: 
Related to https://github.com/SciML/DataDrivenDiffEq.jl/pull/230
> Explicit return of indexed array variables from get_variables

- docs/src/tutorials/converting_to_C.md
The documentation has a previously deprecated use of `build_function` with `CTarget`, where it uses `Array{<:Equation}`. This fixes the problem.
> Fixing docs for `build_function` with `CTarget`

- src/num.jl
- src/utils.jl
I guess `@parameter` is from ModelingToolkit.
I found it confusing to show up in the Documentation here, though I'm not 100% sure the proposed changes are equivalent.
> remove `@parameters` from docstrings

- src/Symbolics.jl
- src/difference.jl
- test/difference.jl
- test/runtests.jl
https://github.com/SciML/ModelingToolkit.jl/issues/1088#issuecomment-872497549
This PR aims to add the `Difference` operator to enable defining fixed discrete step state transitions. 
@YingboMa 
CC: @ChrisRackauckas
> [WIP] Add Difference operator

- Project.toml
- src/Symbolics.jl
- src/variable.jl
- test/macro.jl
This PR solves a bunch of problems:
1. Helps avoid string-based namespacing in MTK: the new `Namespace{T}<:Symobolic{T}` type holds a parent object and a variable the parent object namespaces. We should use this in place of all the ambiguous stuff we have going on.
2. `@variables` now sneakily stores the variable name, so for example, we don't need brittle hacks to identify `x[1:10](t)` and extract the name from it. This also makes it equally less hacky to walk a system of equations and extract the list of variables that is closer to what the user intended.
3. Bring back the old behavior of `@variables x[1:3, 3:6]` in the form of `variables(:x, 1:3, 3:6)`
basically this PR makes everything one hundred times better.
> Namespacing, deterministic variable names, subscripted variables

- src/variable.jl
There was the same exact declaration twice, which causes precompilation warnings. I believe this redundancy is unnecessary.
> Remove redundancy in `variable.jl`

- src/build_function.jl
```julia
julia> Base.Threads.Task === Task
true
julia> Base.Threads.schedule === schedule
true
```
So, using these names is not useful for parallel execution.
I just added a line `task.sticky = false` to run it on threaded workers. It's not a public API but I'm assuming there is a reason why `@spawn` cannot be used here.
> Use threads in MultithreadedForm

- src/Symbolics.jl
- src/diff.jl
- src/integral.jl
moves `Integral(x, ClosedInterval(0,1))` to  `Integral(x, x in ClosedInterval(0,1))`
> Moving Integral domain type from Domain to VarDomainPairing

- src/variable.jl
- test/macro.jl
previously it would think the ndims in the test case is `1`.
> Compute ndims from runtime length of axes in `@variables`

- src/equations.jl
- test/diff.jl
currently (3.4.1) if you try to substitute on `Vector{Equation}` it defaults to the SU fallback, but doesn't actually do anything, 
ex: 
```julia
julia> using ModelingToolkit, Test, Symbolics
julia> @parameters σ=10 ρ=28 β=8/3
3-element Vector{Num}:
σ
ρ
β
julia> @variables t x(t)=1 y(t)=0 z(t)=0
4-element Vector{Num}:
t
x(t)
y(t)
z(t)
julia> D = Differential(t)
(::Differential) (generic function with 2 methods)
julia> eqs = [D(x) ~ σ*(y-x),
D(y) ~ x*(ρ-z)-σ]
2-element Vector{Equation}:
Differential(t)(x(t)) ~ σ*(y(t) - x(t))
Differential(t)(y(t)) ~ x(t)*(ρ - z(t)) - σ
julia> sub_eqs = substitute(eqs, Dict(σ=>1))
2-element Vector{Equation}:
Differential(t)(x(t)) ~ σ*(y(t) - x(t))
Differential(t)(y(t)) ~ x(t)*(ρ - z(t)) - σ
julia> map(x->substitute(x, Dict(σ=>1)), eqs)
2-element …
```
> fix substitute for Equation[]

- src/difference.jl
Ideally, this function should be deprecated and renamed to the standard term `Shift`
> Update `DiscreteUpdate` docstring

- src/arrays.jl
- src/diff.jl
- test/arrays.jl
This approach still fails for Arr variables that do not contain size information, but it prevents returning the wrong result which is a current problem. Partly addresses #439 
This PR also introduces som `@test_skip` which should pass, but currently throws errors.
> add jacobian method for Arr

- src/build_function.jl
- test/build_function.jl
This avoids calling `map(x->_make_array...` to recursively look for sparse arrays, and tries to use `nzmap` which leaves the zeros untouched. This eventually avoids calls to `iszero` which is very slow...
should fix the slow build_function generation in https://github.com/JuliaSymbolics/Symbolics.jl/issues/435 (it goes to < 16secs first and <1sec subsequent runs.)
> more conscious sparse array handling in build_function

- src/Symbolics.jl
- src/extra_functions.jl
- src/register.jl
- test/diff.jl
- test/macro.jl
```julia
julia> @register foo(x::AbstractArray)::Real
julia> @variables x[1:9]
1-element Vector{Symbolics.Arr{Num, 1}}:
x[1:9]
julia> foo(x)
foo(x[1:9])
julia> foo(x) |> typeof
Num
julia> foo([1])
ERROR: MethodError: no method matching foo(::Vector{Int64})
Closest candidates are:
foo(::SymbolicUtils.Symbolic{var"#s25"} where var"#s25"<:AbstractFoo, ::SymbolicUtils.Symbolic{var"#s24"} where var"#s24"<:Real) at /home/shashi/.julia/dev/Symbolics/src/wrapper-types.jl:126
foo(::FooWrap, ::SymbolicUtils.Symbolic{var"#s23"} where var"#s23"<:Real) at /home/shashi/.julia/dev/Symbolics/src/wrapper-types.jl:126
foo(::AbstractFoo, ::SymbolicUtils.Symbolic{var"#s26"} where var"#s26"<:Real) at /home/shashi/.julia/dev/Symbolics/src/wrapper-types.jl:126
...
Stacktrace:
[1] top-level scope
```
Also: …
> WIP: @register changes

- src/Symbolics.jl
- test/overloads.jl
```julia
using DifferentialEquations, SnoopCompile
function lorenz(du,u,p,t)
du[1] = 10.0(u[2]-u[1])
du[2] = u[1]*(28.0-u[3]) - u[2]
du[3] = u[1]*u[2] - (8/3)*u[3]
end
u0 = [1.0;0.0;0.0]
tspan = (0.0,100.0)
prob = ODEProblem(lorenz,u0,tspan)
alg = Rodas5(chunk_size = Val{3}(), linsolve = DiffEqBase.LUFactorize())
tinf = @snoopi_deep solve(prob,alg)
```
Before:
```julia
InferenceTimingNode: 1.388166/12.746425 on Core.Compiler.Timings.ROOT() with 2 direct children
```
After:
```julia
```
Fixes https://github.com/SciML/DifferentialEquations.jl/issues/785
> Remove destructive invalidation and fix compile times

- src/num.jl
- test/overloads.jl
Adds a method for `Base.:^(::Irrational{:ℯ}, x::Num)` so that Symbolics can parse `ℯ^x` (where ℯ is Julia's built-in Euler's constant) as `exp(x)`. I figured I'd just make this PR after seeing someone run into an error on SO from trying to do
```julia
@variables x
ℯ^x
```
> Add method for `^(::Irrational{:ℯ}, x::Num)`

- docs/src/manual/functions.md
`@register` is deprecated, but that didn't make its way to the docs: https://github.com/JuliaSymbolics/Symbolics.jl/pull/457
> Fix docs of register_symbolic macro

- src/build_function.jl
- test/build_function.jl
Fixes https://github.com/JuliaSymbolics/Symbolics.jl/issues/136 . Gives:
```julia
using LinearAlgebra
using SparseArrays
@variables x y
N = 8
A = sparse(Tridiagonal([x^i for i in 1:N-1],[x^i * y^(8-i) for i in 1:N], [y^i for i in 1:N-1]))
build_function(A,[x,y],parallel=Symbolics.MultithreadedForm())[2]
```
```julia
function (var"##out#283", var"##arg#282")
#= C:\Users\accou\.julia\packages\SymbolicUtils\0Fgyc\src\code.jl:278 =#
#= C:\Users\accou\.julia\packages\SymbolicUtils\0Fgyc\src\code.jl:279 =#
let x = var"##arg#282"[1], y = var"##arg#282"[2]
#= C:\Users\accou\.julia\packages\Symbolics\JhAD8\src\build_function.jl:243 =#
(Symbolics.var"#noop#472"())(map(fetch, (begin
#= C:\Users\accou\.julia\packages\Symbolics\JhAD8\src\build_function.jl:235 =#
let
#= …
```
> Fix Sparse Multithreaded Form

- src/diff.jl
```julia
julia> using Symbolics
julia> @variables t u(t)
2-element Vector{Num}:
t
u(t)
julia> N = 20
20
julia> D = Differential(t)
(::Differential) (generic function with 2 methods)
julia> DN = D^N
Differential(t) ∘ Differential(t) ∘ Differential(t) ∘ Differential(t) ∘ Differential(t) ∘ Differential(t) ∘ Differential(t) ∘ Differential(t) ∘ Differential(t) ∘ Differential(t) ∘ Differential(t) ∘ Differential(t) ∘ Differential(t) ∘ Differential(t) ∘ Differential(t) ∘ Differential(t) ∘ Differential(t) ∘ Differential(t) ∘ Differential(t) ∘ Differential(t)
julia> @time DN(u)
0.045852 seconds (128.03 k allocations: 7.480 MiB, 99.69% compilation time)
Differential(t)(Differential(t)(Differential(t)(Differential(t)(Differential(t)(Differential(t)(Differential(t)(Differential(t)(Differential(t)(Diffe …
```
> Fix D^t compile time problem

- test/arrays.jl
I would like to fix #509, namely this test case:
```julia
@variables x[1:3]
substitute(x[1], Dict([x => [1, 0, 0]]))
```
My idea is to find all indexing subexpression inside `expr`, collect them and for each of them adding a corresponding substitution in the dict before calling SymbolicUtils.substitute.
In the previous example,
```substitute(x[1], Dict([x => [1, 0, 0]]))```
would become
```substitute(x[1], Dict([x => [1, 0, 0], x[1] => 0))```
(only terms actually appearing in the expression are added to the substitution dict).
Unfortunately I don't know my way around the code. Say I have `@variables x[1:3]`, and I stumble upon `x[1]`. How can I create from it a Symbolic.Arr called x with the right dimensions in order to search the substitution Dict for its presence?
┆Issue is synchronized …
> Additional test for array substitution

- src/arrays.jl
- src/diff.jl
- src/utils.jl
- src/variable.jl
- test/arrays.jl
- test/diff.jl
- test/macro.jl
- test/overloads.jl
- test/runtests.jl
Added the new variation of the calling convention without removing the old version (precursor release to #620, this now prints warnings like this:
```
┌ Warning: Array of function variable (x[1:4])(t) is deprecated. Use dependent array variables instead, for example: (x(t))[1:4]. Note that this changes the semantics of the variable, the deprecated semantics will be deleted in the next release in order to facilitate better implementation of various features of Symbolics.
┌ Warning: Array of function variable (p[1:4])(..) is deprecated. Use dependent array variables instead, for example: (p(..))[1:4]. Note that this changes the semantics of the variable, the deprecated semantics will be deleted in the next release in order to facilitate better implementation of various features of …
```
> Dependent array variable convention deprecation

- src/build_function.jl
- test/build_function.jl
For non-scalar functions `build_function` supports a `wrap_code` argument which is used to, for example, generate affect functions taking one argument, `integrator`, that internally use `(integrator.u,integrator.p,integrator.t)`. 
I'm working on adding `DiscreteCallbacks` to ModelingToolkit, and need to generate a scalar function `condition(u,t,integrator)`, where internally we get system parameters from `integrator.p`. So now need a wrapper for the scalar version of `build_function` too. With this PR, I think I've got discrete callbacks working.
> wrap_code for scalar functions to enable DiscreteCallbacks in ModelingToolkit

- src/semipoly.jl
- test/semipoly.jl
```
@variables x y
sqrt_x = sqrt(x)
deriv = expand_derivatives(Differential(x)(sqrt_x)) # (1//2)*(sqrt(x)^-1)
expr = substitute(deriv, Dict(sqrt_x => y)) # (1//2)*(y^-1)
dict, residual = semipolynomial_form(expr, [x, y], Inf)
dict
Dict{SymbolicUtils.Pow{Real, SymbolicUtils.Sym{Real, Base.ImmutableDict{DataType, Any}}, Int64, Nothing}, Rational{Int64}} with 1 entry:
y^-1 => 1//2
```
As shown in the above, `semipolynomial_form` returns the fake monomial `y^-1` whose exponent `-1` is negative.
In principal, one cannot create a `SymbolicUtils.Pow` object with `exp` $<0$. For example,
```
julia> a = x^-3
(1 / x)^3
julia> dump(a; maxdepth = 4)
Num
val: SymbolicUtils.Pow{Real, SymbolicUtils.Div{Real, Int64, SymbolicUtils.Sym{Real, Base.ImmutableDict{DataType, Any}}, Nothing}, …
```
> Fix `semipolynomial_form` in case of a `SymbolicUtils.Pow` with a negative exponent

- src/semipoly.jl
- test/semipoly.jl
The non-polynomial residual returned by `semipolynomial_form(expr, vars, degree)` does not maintain the `SymbolicUtils.Symbolic` subtype of the input `expr` when `expr` does not contain polynomial and its top-level operation is not `+`.
This PR fixes this issue.
The following is an example that triggers the bug.
```
@variables x y
expr = 9 * 7^y * sin(x)^4 * tan(x + y)^3
value = Symbolics.unwrap(expr)
```
`value`, the internal of `expr`, is a `SymbolicUtils.Mul`.
```
julia> dump(value; maxdepth = 1)
SymbolicUtils.Mul{Real, Int64, Dict{Any, Number}, Nothing}
coeff: Int64 9
dict: Dict{Any, Number}
sorted_args_cache: Base.RefValue{Any}
hash: Base.RefValue{UInt64}
metadata: Nothing nothing
julia> value.dict
Dict{Any, Number} with 3 entries:
sin(x)     => 4
tan(x + y) => 3
7^y …
```
> Fix Symbolic type of residual from `semipolynomial_form` with a single non-polynomial no-addition input

- src/Symbolics.jl
- src/utils.jl
- test/coeff.jl
- test/degree.jl
- test/runtests.jl
Hi,
This is a proposition in order to obtain the coefficients from `Symbolic` expressions (focusing on monomials).
```julia
@variables a x y
julia> coeff(2a, x)
0
julia> coeff(a*x, x)
a
julia> coeff(3x + 2y, x)
3
julia> coeff(x * y, x)
y
julia> coeff(x^2 + y, x^2)
1
```
Fix https://github.com/JuliaSymbolics/Symbolics.jl/issues/216.
Fix https://github.com/JuliaSymbolics/Symbolics.jl/issues/374.
Fix https://github.com/JuliaSymbolics/Symbolics.jl/issues/236.
I've also rewritten `degree` as a `nfc` in the same pattern as `coeff` for consistency (~~enhance~~ after https://github.com/JuliaSymbolics/Symbolics.jl/pull/241).
~~Open question (which needs to be settled for `coeff` & `degree`): how do we handle `SymbolicUtils.Div` ?~~
~~`degree(x / y, x)` currently throws a …
> implement `coeff`

- src/utils.jl
1. avoids creating a vector due to broadcast
2. avoids sorting arguments
3. make use of the data structures of `Mul` and `Add`
> Refactor `degree` & `coeff` for `Add` & `Mul`

- src/diff.jl
`hessian_sparsity` expects a single scalar-valued function, but the type of the 1st argument in its docstring signature shows `AbstractVector`.
https://github.com/JuliaSymbolics/Symbolics.jl/blob/ab7e1aa725f5599e1fb9a9b6e76beb5e392f820c/src/diff.jl#L620-L622
> Fix `hessian_sparsity` docstring signature

- src/domains.jl
Shouldn't change the behavior, but might prevent run time dispatch.
> fix type parameter declaration

- src/latexify_recipes.jl
See the discussion in https://github.com/fonsp/Pluto.jl/issues/488 and https://github.com/stevengj/LaTeXStrings.jl/issues/50 and https://github.com/fonsp/Pluto.jl/pull/1164. IIUC, @stevengj makes the argument that no `MIME"text/latex"` output can be assumed to be a single LaTeX statement, which is reasonable, and the natural consequence of that is that no display environment using `MIME"text/latex"` should assume that the output is a single expression and put `$$ x $$` for you. And if that's the case, it's the job the displayer to output properly formatted TeX with the display environments defined. That is sensible, and we just need to make sure that Symbolics and ModelingToolkit does that everywhere.
> Fix `MIME"text/latex"` output to ensure it's in a TeX environment

- src/variable.jl
this helps a bit with discoverability of the metadata types defined in MTK.
i want a way to take a table of parameters/variables from (and to) excel/csv
its not absolutely necessary, i can hack it without, but this would make the code a bit cleaner
> add a variablemetadata supertype for downstream metadata types

- src/linear_algebra.jl
- src/num.jl
This PR extends `det`, `lu`, `inv` and `SparseCSC` to the matrices of `Complex{Num}`.
It solves Issue #861
> Matrix operations for `Matrix{Complex{Num}}`

- docs/src/manual/derivatives.md
- src/diff.jl
- The function `sparsehessian_vals` is similar to `sparsejacobian_vals` (#710) 
- I also started to fix (#859) but I don't know what I should modify in this function:
```julia
function hessian_sparsity(expr, vars::AbstractVector; full::Bool=true)
@assert !(expr isa AbstractArray)
expr = value(expr)
u = map(value, vars)
idx(i) = TermCombination(Set([Dict(i=>1)]))
dict = Dict(u .=> idx.(1:length(u)))
f = Rewriters.Prewalk(x->haskey(dict, x) ? dict[x] : x; similarterm=basic_simterm)(expr)
lp = linearity_propagator(f)
S = _sparse(lp, length(u))
S = full ? S : tril(S)
end
```
cc @tmigot
> Add sparsehessian_vals function

- src/array-lib.jl
Dot-products seem to be handled incorrectly: https://github.com/JuliaSymbolics/Symbolics.jl/issues/459
From my understanding, this is not merely a displaying error:
The old `return Term{S}(*, [A, b])` in `_matvec(A,B)` would become an incorrect SymbolicUtils `Mul` construct when `scalarize` is called.
In this fix, I handle dot-products like any matrix-vector product. If `isdot(A,b)==true`, I return the indexed result, so that it behaves like a scalar when `wrap`ed.
> Change Scalarization behavior of dot-products, fix issue #459

- src/array-lib.jl
- test/arrays.jl
Wrap `LinearAlgebra.dot` so that it dispatches on symbols representing scalars that are not wrapped in `Num`.
See https://github.com/JuliaSymbolics/Symbolics.jl/issues/831 for an example.
That example is also included in the test suite.
> "Fix" for #831 -- specialize `LinearAlgebra.dot` to dispatch on `Symbolic{<:Number}`

- src/register.jl
- test/macro.jl
Closes #806 
This technically works:
```julia
julia> using Symbolics
julia> module Foo
struct Bar
x::Float64
end
(f::Bar)(x) = f.x*x
end
julia> @register_symbolic (f::Foo.Bar)(x)
```
The required changes are due to `typeof((f::Foo.Bar))` not working in (what is now) line 91. This also requires the struct be registered as above and not as `(::Foo.Bar)(x)` so that it can be called in `eval_method`. An `@assert` has been added to ensure this.
The only issue is that the result cannot be printed:
```julia
julia> @variables t x(t)
julia> f = Foo.Bar(3)
julia> f(t) # or f(x)
Error showing value of type Num:
ERROR: MethodError: no method matching nameof(::Main.Foo.Bar)
Closest candidates are:
nameof(::SymbolicUtils.BasicSymbolic) at ~/.julia/packages/SymbolicUtils/Vzo2s/src/types.jl:222 …
```
> Allow registering callable structs

- src/register.jl
> don't overwrite s and s_syms in register macro

- src/latexify_recipes.jl
This PR fixes #865 .
Basically, I've extended existing methods for `show(io::IO, ::MIME"text/latex", x)` to include `Complex{Num}` and `Array{Complex{Num}}`.
In addition to that, I have altered the `latexify_recipe` for `::Complex{Num}` to drop the zero imaginary part.
Otherwise it can lead to absurd expressions such as `0i` instead of `0`, or `ω₀+0i` instead of `ω₀` for `ω₀::Num`.
Compare
and
In addition to that, we could improve it further. In the case where there is a single monomial multiplied by imaginary `i`, the parenthesis can be dropped. Also, it would be nice to put `i` directly between the numerical coefficient and the product of variables, as it is done by humans.
In regards to that, I have a question: **is it possible to distinguish `Num` with single term and with multiple …
> Fixes latexify for complex symbolic numbers and arrays.

- src/linear_algebra.jl
This PR adds the method `inv(A::AbstractMatrix{<:RCNum}; laplace=true)`, which computes the inverse matrix via adjugate matrix (composed of determinants of minors of the original matrix).
Currently there is a problem that `inv(A)` always invokes `LinearAlgebra.inv(A::StridedMatrix{T}) where T` version of inverse. If you want to use the method from this PR, explicit keyword `laplace=true` has to be added.
This is attributed to the fact that `StridedMatrix{T}` seems to be more specific type than `AbstractMatrix{<:RCNum}`.
I am not sure how to resolve this issue. Nevertheless, this PR can already be used as it is.
> Symbolic matrices inverse via adjugate matrix. Implements #864

- src/num.jl
`hash` should always return a `UInt`, and `_iszero` and `_isone` should always return a `Bool`.
> Type asserts for `hash`, `_iszero`, and `_isone`

- src/utils.jl
Calling coeff on expressions with symbolic division now throws a more informative DomainError instead of a StackOverflowError.
Working on making the function actually work for such expressions.
> coeff throws DomainError for expressions with division

- src/build_function.jl
I found this when looking at precompilation warnings
```
1 dependency had warnings during precompilation:
┌ Symbolics [0c5d862f-8b57-4792-8d23-62f2024744c7]
│  WARNING: Code.get_symbolify is deprecated, use get_rewrites instead.
│    likely near /home/runner/.julia/packages/Symbolics/BQlmn/src/build_function.jl:130
└  
```
in https://github.com/ranocha/BSeries.jl/pull/153
> replace deprecated get_symbolify by get_rewrites

- src/Symbolics.jl
- src/error_hints.jl
Fixes https://github.com/SciML/ModelingToolkit.jl/issues/2320
```julia
using ModelingToolkit, OrdinaryDiffEq
@variables t x(t)
@parameters y
ff(x) = x + y
@register_symbolic ff(x)
D = Differential(t)
eqs = [D(x) ~ ff(x)]
@named sys = ODESystem(eqs,t)
prob = ODEProblem(sys, [x=>1, y=>1], (0.0,1.0))
sol = solve(prob, Tsit5())
```
Example:
```julia
julia> sol = solve(prob, Tsit5())
ERROR: MethodError: no method matching Float64(::Num)
An implict conversion of symbolic Num into a Float64 was encountered. Common causes for this error include:
1. A substitution resulted in numerical values, but is not automatically converted to numerical values. For example:
```julia
@variables x y
result = [1.0]
A = [x x^2
y+x 2x + y]
sub = substitute(A, Dict([x=>2.0, y=>2]))
result[1] = sub[1]
```
The reason …
```
> Add error hint on implicit Float conversion from Num

- .github/workflows/ci.yml
- docs/Project.toml
- docs/make.jl
- docs/src/getting_started.md
- docs/src/index.md
Documentation is not building on old version.
This needs to be fixed before we can continue here.
> start Documenter 1.0 upgrade

- src/extra_functions.jl
- src/register.jl
- src/wrapper-types.jl
- test/registration_without_using.jl
- test/runtests.jl
Fixes https://github.com/JuliaSymbolics/Symbolics.jl/issues/1023
> Fix registration without using

- src/extra_functions.jl
- test/overloads.jl
Closes https://github.com/JuliaSymbolics/Symbolics.jl/issues/1028.
Uses @ChrisRackauckas's suggestion on how to handle this.
> change binomial registration

- Project.toml
- ext/SymbolicsForwardDiffExt.jl
- test/forwarddiff_symbolic_dual_ops.jl
- test/runtests.jl
This is a first attempt at resolving https://github.com/JuliaSymbolics/Symbolics.jl/issues/1032.
The easiest way to resolve the issue seems to be to copy the relevant method definitions from [ForwardDiff](https://github.com/JuliaDiff/ForwardDiff.jl/blob/master/src/dual.jl), which is what is done in this PR.
Unfortunately this introduces a lot of code duplication. An alternative approach would be to convert the method definition loops in https://github.com/JuliaDiff/ForwardDiff.jl/blob/master/src/dual.jl into functions that take a list of the ambiguous types as argument. However, this requires more changes to ForwardDiff in order to prevent existing methods from getting overwritten (e.g. [here](https://github.com/JuliaDiff/ForwardDiff.jl/blob/master/src/dual.jl#L139)).
Let me know if you'd …
> Resolve Symbolics.Num - ForwardDiff.Dual  ambiguities

- src/equations.jl
and compactify printing which now becomes a bit longer
example:
```julia
julia> equations(ff)
17-element Vector{Equation}:
initial_state(state1)
state1 → state2 if (activeState(state1₊stateD) & activeState(state1₊stateY)) [immediate: 1, reset: 1, sync: 0, prio: 1]
state2 → state1 if (v(t) >= 20) [immediate: 1, reset: 1, sync: 0, prio: 1]
initial_state(stateA)
stateA → stateB if (v(t) >= 6) [immediate: 1, reset: 1, sync: 0, prio: 1]
stateB → stateC if (v(t) == 0) [immediate: 1, reset: 1, sync: 0, prio: 1]
stateC → stateD if (count(t) >= 2) [immediate: 1, reset: 1, sync: 0, prio: 1]
stateC → stateA if (true) [immediate: 1, reset: 1, sync: 0, prio: 2]
initial_state(stateX)
stateX → stateY if (stateX₊i(t) > 20) [immediate: 1, reset: 1, sync: 0, prio: 1]
Shift(t, 1)(v(t)) ~ 2 + v(t)
Shift(t, …
```
> print condition in show(::Transition)

- src/struct.jl
`Struct <: Real` is required for tracing.
> Add symbolic_getproperty

- src/register.jl
This warning is involved in a weird Catalyst bug:
https://github.com/SciML/Catalyst.jl/issues/788
@ChrisRackauckas suggested the simplest way to get rid of it would be to just fully deprecate the register macro.
> remove deprecation warning for @register

- src/diff.jl
The old docstring that motivated this PR was
```
help?> Symbolics.derivative
derivative(O, v; simplify)
A helper function for computing the derivative of an expression with respect to var.
```
> Accurately refer to function argument names in docstrings

- src/arrays.jl
- test/arrays.jl
This is required in MTK to be able to generate functions for expressions like
```julia
@variables x[1:3] p[1:3, 1:3]
expr = bar(x, 3p)
```
Where `bar` is a `@register_array_symbolic` function
> feat: support similarterm for arrayop

- Project.toml
- docs/make.jl
- docs/src/manual/limits.md
- src/Symbolics.jl
- src/limits.jl
- test/limits.jl
This has a slightly different API than SymbolicLimits itself because I aspire to make the heuristics good enough that the returned assumptions are not worth user verification in most cases and should not be returned by default.
> Add dep on SymbolicLimits.jl and export `limit`

- src/utils.jl
- test/coeff.jl
Since the bool sym == nothing is used repeatedly throughout the function, and `coeff(expression, nothing)` returns the coefficient of a constant (such as `1` in `x^2 +2x + 1`). A user may want to use `coeff(expression, x^0)` for readability's sake to get that constant.
> Fixed output of coeff(expression, x^0) or equivalent to coeff(expression, 1)

- src/Symbolics.jl
`@register` was removed in favor of `@register_symbolic` and its deprecation warning is also removed in https://github.com/JuliaSymbolics/Symbolics.jl/pull/1071
> refactor: remove undefined export `@register`

- src/register.jl
- test/macro.jl
> fix: make `@register_array_symbolic` overload `promote_symtype`

- docs/src/manual/functions.md
- test/coeff.jl
`coeff` works with symbolic and non-integral powers. However, this case is not covered in unit tests.
Add tests to preserve this functionality into the future.
> More test coverage for coeff

- src/domains.jl
When integrating Symbolics.jl with Latexify and ImageInTerminal, the following warning is emitted:
```
WARNING: method definition for supremum at /Users/nathompson7/.julia/packages/Symbolics/HDE84/src/domains.jl:22 declares type variable T but does not use it.
```
Fix it by removing the variable declaration.
> [Trivial] Remove warning

- src/Symbolics.jl
- src/rewrite-helpers.jl
- test/rewrite_helpers.jl
The current implementation causes occasional ambiguity errors. This fixes that.
> A fix for `occursin`

- src/diff.jl
- test/diff.jl
> Add support for Differential(...)^0

- src/rewrite-helpers.jl
- test/rewrite_helpers.jl
Fixes https://github.com/JuliaSymbolics/Symbolics.jl/issues/1175
> Automatically unwrap and wrap Nums for rule application

- src/utils.jl
This pull request addresses an error encountered due to the ambiguity of the `head` function. Both the DataStructures and TermInterface packages export `head`, leading to a warning, ultimately an `UndefVarError` within the Symbolics module and the precompilation failure in ModelingToolkit integration test CI https://github.com/JuliaSymbolics/SymbolicUtils.jl/actions/runs/9640298551/job/26583838382?pr=615 in PR https://github.com/JuliaSymbolics/SymbolicUtils.jl/pull/615.
To resolve this, an instance of `head(O)` within Symbolics.jl has been replaced with `TermInterface.head(O)`.
> Fix: Resolve `head` ambiguity and prevent `UndefVarError` and precompilation failure

- Project.toml
- src/build_function.jl
- src/latexify_recipes.jl
- src/semipoly.jl
- src/solver.jl
- src/utils.jl
- src/variable.jl
This PR migrates Symbolics.jl from the deprecated `unsorted_arguments` to `arguments`, following the changes introduced in PR https://github.com/JuliaSymbolics/SymbolicUtils.jl/pull/615.
Specifically, this PR:
- Replaces all instances of `unsorted_arguments` with `arguments` to align with the updated SymbolicUtils API.
- Updates functionalities that require sorted arguments, such as printing, LaTeXifying, and code generation, to use the `sorted_arguments` instead of `arguments`.
This change ensures compatibility with the latest version of SymbolicUtils.jl and eliminates deprecation warnings.
> Refactor: Migrate from deprecated `unsorted_arguments` to `arguments`

- src/latexify_recipes.jl
- test/latexify.jl
- test/latexify_refs/indices1.txt
- test/latexify_refs/indices2.txt
The way indices were previously latexified was a hack which apparently worked in jupyter notebooks for single digit indices, but did not produce real LaTeX code and broke down for double digit indices.
Odds are, this looks slightly different from before -- if there is a strong preference perhaps it could be adjusted but this is really how it's supposed to be written.
Also adds a bit of configurability, in case someone prefers `x[1,1]` syntax.
Closes  #1181, closes korsbo/latexify.jl#293
> Latexify indices correctly

- src/Symbolics.jl
Use of a symbolic expression in a boolean context is a rather common user mistake, this PR adds a hint with possible fixes
> add error hint on Num in boolean context

- src/num.jl
- test/runtests.jl
- test/show.jl
With this PR, arrays that includes `e` or `f` are displayed correctly.
```julia
julia> using Symbolics
julia> r = @variables a b c d e f g h i j
10-element Vector{Num}:
a
b
c
d
e
f
g
h
i
j
julia> m = [a b c d
b e f g
c f h i
d g i j]
4×4 Matrix{Num}:
a  b  c  d
b  e  f  g
c  f  h  i
d  g  i  j
julia> m *= [1, 2, 3, 4]
4-element Vector{Num}:
a + 2b + 3c + 4d
b + 2e + 3f + 4g
c + 2f + 3h + 4i
d + 2g + 3i + 4j
```
> Fix display array containing `e` or `f`

- src/num.jl
Removes an ambiguity with the Base definition: `promote_rule(::Type{BigFloat}, ::Type{<:Real})`
> add promote between `BigFloat` and `Num`

- src/utils.jl
- test/runtests.jl
- test/utils.jl
The existing `get_variables` function does not guarantee the order of the returned variables. This can be inconvenient in cases where ordering is desired.
This PR introduces a new keyword argument `sort` to the `get_variables` function. By default, `sort` is set to `false`, preserving the previous behavior. Setting `sort = true` will result in the returned variables being sorted.
> Add sorting option to `get_variables` function

- src/utils.jl
- test/coeff.jl
This is a partial fix to issue [#925](https://github.com/JuliaSymbolics/Symbolics.jl/issues/925), making coeff usable on divisions if the target symbol is not in the denominator.
This PR will result in `coeff(x / y, x)` returning `1 / y`, instead of throwing an error, while `coeff(x / (y + x), x)` will still throw a not implemented error.
> fix coeff on divisions

- src/solver/ia_helpers.jl
- test/solver.jl
> n_func_occ not detecting a*x

- ext/SymbolicsGroebnerExt.jl
Currently, `symbolic_solve`, which uses the Groebner.jl package extension, takes about 20 seconds to run for the first time on my laptop for very simple linear equations. I've added precompilation statements (using PrecompileTools) in the file `SymbolicsGroebnerExt.jl` to significantly reduce the latency for users, following some discussions on Discourse:
https://discourse.julialang.org/t/new-symbolic-solver-for-symbolics-jl/
> Precompile `symbolic_solve` in `SymbolicsGroebnerExt.jl`

- ext/SymbolicsGroebnerExt.jl
- ext/SymbolicsNemoExt.jl
- src/solver/main.jl
- test/solver.jl
Now symbolic_solve supports expressions such as
```julia
symbolic_solve((x - y) * (x - z), [x, y, z])
```
and similar. Also, added precompile tool hooks (i think they're called that) to nemo.
```julia
julia> @time symbolic_solve([x^2 - a^2, x + a], x)
7.805655 seconds (17.50 M allocations: 1.169 GiB, 2.76% gc time, 99.79% compilation time: <1% of which was recompilation)
1-element Vector{SymbolicUtils.BasicSymbolic{Real}}:
-a
```
```julia
julia> @time symbolic_solve([x^2 - a^2, x + a], x)
0.511816 seconds (1.28 M allocations: 85.815 MiB, 3.62% gc time, 98.22% compilation time)
1-element Vector{SymbolicUtils.BasicSymbolic{Real}}:
-a
```
> Fixed some bugs, symbolic_solve(single expr, [multiple_vars]), and precompiled nemo

- src/latexify_recipes.jl
- test/latexify.jl
- test/latexify_refs/complex4.txt
At the moment, `latexify` fails on some complex expressions involving Symbolics.
For example,
```
using Symbolics, Latexify
latexify(im * Symbolics.Term(sqrt, [2]))
```
currently results in an error.
This PR is a small fix that resolves this error with minimal changes to the existing code. More work is probably needed to ensure complex pre-factors always display nicely.
> fix latexify on complex expressions

- src/utils.jl
- test/coeff.jl
Currently `coeff(p, sym)` silently returns a wrong result when `sym` is a product, as reported by issue #1041. This commit fixes the issue by iteratively computing the coefficient w.r.t. each term in the product.
> Fix `coeff(p, sym)` when `sym` is a product (issue #1041)

- src/variable.jl
I'm not sure why this was specifically guarded in a condition before
> fix: call `transform` on dependent array variables in `@variables`

- test/utils.jl
Adds missing `@test` macros from https://github.com/JuliaSymbolics/Symbolics.jl/pull/1242. Also changed the first test to test `isa Rational{Int}` since that's what the actual result is, but I can't tell if you do actually want that to be a `Float64`.
> Add missing `@test`s in testset

- ext/SymbolicsForwardDiffExt.jl
- test/forwarddiff_symbolic_dual_ops.jl
This is another attempt at fixing https://github.com/SciML/ModelingToolkit.jl/issues/2997 by addressing the actual root cause of the issue, which is described with a minimal example in https://github.com/JuliaSymbolics/Symbolics.jl/issues/1246. Following https://github.com/JuliaSymbolics/Symbolics.jl/pull/1036, I have also copied ForwardDiff's `isequal()` definition to resolve the type ambiguity.
>  Resolve isequal(Num, ForwardDiff.Dual) ambiguity

- src/solver/main.jl
Added notes to inform users about the necessity of using Nemo and Groebner when using `symbolic_solve`
> symbolic_solve docstring update (using Nemo and using Groebner)

- src/solver/postprocess.jl
- test/solver.jl
Now the example from
https://discourse.julialang.org/t/comparing-symbolics-jl-with-mathematica/118656
simplifies to
```julia
julia> symbolic_solve(-279//16 + x^2, x)
2-element Vector{SymbolicUtils.BasicSymbolic{Real}}:
(3//4)*√(31//1)
(-3//4)*√(31//1)
```
> Simplify sqrt((A/B)^2) => A/B

- Project.toml
- test/downstream/Project.toml
- test/downstream/modeling_toolkit_utils.jl
NT.get_unit assumes DynamicQuantities, to use Unitful use MT.UnitfulUnitCheck.get_unit.
> Fix downstream test

- src/latexify_recipes.jl
- test/latexify.jl
> Suppress identity transformation in Latexified expressions 

- src/diff.jl
- test/diff.jl
As reported in #1085, e.g.
```
@variables x
Symbolics.derivative(sqrt, x)
```
returns 0, when it should return the derivative of `sqrt` (which is not zero of course).
Also added a catching method to throw for non-`Num` second input when first input `isa Function`.
@ChrisRackauckas mentions in #1085 to add a catching method to report "`derivative` not supported for `typeof(f)`" which I couldn't understand, I'll need further explanation? I thought it made more sense to report lack of support for `x isa Any` catch.
He also mentions a check on if `x` is symbolic in any form, I'm also not sure what that means, i.e. what other forms than `Num` are supported? `Complex{Num}` and `Integer{Num}`? (Which errors on input to `f` anyway.)
Happy to make changes as desired.
> Fix false positive result of passing a `Function` to `derivative`

- docs/src/manual/solver.md
- ext/SymbolicsGroebnerExt.jl
- src/solver/main.jl
- test/solver.jl
Now, alex's latest issue #1235 's output is returned as 
```julia
julia> symbolic_solve([(x - y) * (x - z) * (y - z)], [x,y,z])
2-element Vector{Dict{Num, Any}}:
Dict(x => y)
Dict(x => z)
```
instead of 
```julia
julia> symbolic_solve([(x - y) * (x - z) * (y - z)], [x,y,z])
2-element Vector{Dict{Num, Any}}:
Dict(z => z, y => y, x => y)
Dict(z => z, y => y, x => z)
```
Also, a warning was added for non-cyclic polynomial systems for our multivar solver. Alex and i plan to implement its solution in the near future.
> changed output format of zero dimension sols

- ext/SymbolicsGroebnerExt.jl
- ext/SymbolicsNemoExt.jl
- src/solver/main.jl
- src/solver/nemo_stuff.jl
- test/solver.jl
Since now `solve_multivar` can handle all cases solved by `solve_multipoly`, therefore the GCD usage is unnecessary given Groebner basis can handle more generalized input (this [pr](https://github.com/JuliaSymbolics/Symbolics.jl/pull/1237) for example).
> removed solve_multipoly

- .typos.toml
- src/solver/main.jl
- src/solver/preprocess.jl
- test/solver.jl
> Simplifying fractions before solving

- Project.toml
- src/variable.jl
- test/macro.jl
- test/overloads.jl
Draft while the other PRs in https://github.com/SciML/ModelingToolkit.jl/issues/2910 are written, so that the entire thing can be tested together.
> feat: add support for typed function symbolics

- src/utils.jl
- test/arrays.jl
- test/diff.jl
The old behavior caused bugs in MTK.
> feat: improve `diff2term` for array symbolics

- test/semipoly.jl
The testing expression generator generates expressions of type `Symbolics.BasicSymbolic{Number}` when all the selected variables are of that type (generated by `@syms` instead of `@variables`).
Add a method to wrap these expressions with a `Num` before checking for cancelation.
> Handle `BasicSymbolic` expressions in test

- src/Symbolics.jl
This is a useful function to have, especially with ModelingToolkit.jl because sometimes variables from MTK are written like `x(t)` and other times they're `x`, so being able to strip out the `(t)` with `escape=true` is nice.
> export `tosymbol`

- src/arrays.jl
- test/arrays.jl
- test/build_function.jl
Close https://github.com/SciML/ModelingToolkit.jl/issues/2720
> fix: fix `maketerm` and `toexpr` for `ArrayOp`

- docs/src/examples/perturbation.md
This updates the perturbation example to use a more recent feature set of Symbolics.jl. Namely
- `Symbolics.coeff` replaces most of the code in `collect_powers` and
- `symbolic_linear_solve` is used instead of `solve_for`.
It also fixes some minor problems:
- the link to the perturbation example on differential equations was dead
- and the code on how to order the solution of the Kepler-equation by orders of $M$ was wrong.
If #1291 is fixed, one could also replace `solve_coef` completely with `symbolic_solve` `using Groebner`.
> update perturbation example

- src/solver/solve_helpers.jl
- test/diff.jl
Expressions returned from `symbolic_solve` would not work with `expand_derivatives` prior to this change.
> fix: define derivatives of ssqrt, scbrt, slog

- src/latexify_recipes.jl
- src/rewrite-helpers.jl
Fixes https://github.com/JuliaSymbolics/Symbolics.jl/issues/1288
> Fix Unicode NAMESPACE_SEPARATOR and subscripts in latex output

- ext/SymbolicsGroebnerExt.jl
Extensions are no longer allowed to assume that their triggers load new extensions at pre-compile time in 1.11 (this was the root cause of a number of pre-compilation / loading "cycle" issues like https://github.com/JuliaLang/julia/issues/55517), so `SymbolicsGroebnerExt` is not allowed to use the methods implemented in `SymbolicsNemoExt` at precompile-time.
That restriction was supposed to be enabled in 1.11.0, but it was unfortunately added in the 1.11.1 patch release.
> Avoid depending on `SymbolicsNemoExt` in `SymbolicsGroebnerExt`

- src/latexify_recipes.jl
- test/latexify_refs/integral1.txt
- test/latexify_refs/integral2.txt
- test/latexify_refs/integral3.txt
`capacitor` makes sense as code but does not make as much sense inside of latex output. When you look at it, it italics each of the letters which makes it look like its c times a times ..., which isn't quite right.
Instead, this uses `\texttt{name}` in order to more clearly delineate a value which is a compound name. Using the fixed width text also looks quite "computer-y" so it has a nice connection to `verbose` and is clearly a "computer variable" in the expression.
> Use fixed width text for compound variable names

- src/latexify_recipes.jl
- test/latexify_refs/integral1.txt
- test/latexify_refs/integral2.txt
- test/latexify_refs/integral3.txt
A possible quick fix for #1314, without changing any behavior for now:
```julia
latexify(@variables t Gᴾ(t) Ω₀ δt αβ b₊Ω0 b₊Ω_0 circuit₊capacitor₊C A B AB)
```
```
L"\begin{equation}
\left[
\begin{array}{c}
t \\
\mathtt{G^P}\left( t \right) \\
\mathtt{\Omega{_0}} \\
\mathtt{{\delta}t} \\
\mathtt{\alpha\beta} \\
\mathtt{b.{\Omega}0} \\
\mathtt{b.\Omega\_0} \\
\mathtt{circuit.capacitor.C} \\
A \\
B \\
\mathtt{AB} \\
\end{array}
\right]
\end{equation}
"
```
> Quick fix Latex rendering

- docs/src/manual/functions.md
- src/Symbolics.jl
- src/inverse.jl
- test/inverse.jl
- test/runtests.jl
Close #1337
I'd like input on the NaNMath inverses. They violate the contract that `inverse(inverse(f)) == f`. We could leave it be, define wrapper functions, or add to the macro the ability to wrap the provided inverse function in an anonymous function. For example,
```julia
@register_inverse f g wrap_inverse = true
```
would define
```julia
var"some_gensymed_name"(x) = g(x)
inverse(::typeof(f)) = var"some_gensymed_name"
inverse(::typeof(var"some_gensymed_name")) = f
```
> feat: add ability to define and query function inverses

- src/num.jl
- src/variable.jl
- test/utils.jl
Close #1342 
I've verified that this also fixes https://github.com/SciML/MethodOfLines.jl/issues/425, with the exception that `interp` needs to be given a value/default.
> feat: support substituting `CallWithMetadata` in expressions

- src/variable.jl
- test/symbolic_indexing_interface_trait.jl
I am very surprised this went unnoticed until now
> fix: fix `symbolic_type` for unwrapped array symbolics

- src/solver/ia_rules.jl
- src/solver/main.jl
- test/solver.jl
Fixed multiplicity bugs by adding correct checking in `solve_univar` and added some tests for `solve_interms_ofvar`. One thing to note; `solve_interms_ofvar` doesnt work with parameters, so say the equations provided are one less than the variables present in the system, it wont get all the other variables in terms of one variable. E.g.:
```julia
julia> eq = (a*x+b)*s^2 - 2s^2 + 2*b*s - 3*s
julia> Symbolics.solve_interms_ofvar(eq, s)
┌ Warning: Infinite number of solutions
└ @ SymbolicsGroebnerExt ~/code/julia/Symbolics.jl/ext/SymbolicsGroebnerExt.jl:228
ERROR: AssertionError: Not a polynomial
```
> Tests for solve_interms_ofvar and bug fixes

- src/variable.jl
> fix: lower default `maxiters` for `fixpoint_sub`

- docs/src/manual/solver.md
- src/inverse.jl
- src/solver/ia_helpers.jl
- src/solver/ia_main.jl
- test/solver.jl
This attempts to:
- Allow `ia_solve` to handle any function that implements the inverse interface instead of hardcoding a list.
- Allow `ia_solve` to handle periodic functions that are not `sin`, `cos` or `tan`.
- Toggle on and off certain behavior in `ia_solve` (specifically, the way it handles periodic functions and complex roots)
@n0rbed I would really appreciate your review on this
> feat: make `ia_solve` modular

- src/solver/ia_main.jl
- test/solver.jl
> feat: allow using `ia_solve` without Nemo

- Project.toml
This allows naughty packages to still be used with us.
> Allow SpecialFunctions v1.8

- src/variable.jl
- test/macro.jl
This enables:
```julia
@variables x y z
args = [x, y, z]
@variables X(args...)
```
which is equivalent to
```julia
@variables X(x, y, z)
```
Currently, the former throws an error. This should enable people to collect e.g. independent variables in a vector, and then using it as dependencies in `@variables`. This will also fix a problem in Catalyst where we no longer can creat observables correctly.
> Enable the creation of variables using `@variables X(vec...)`

- src/latexify_recipes.jl
- test/latexify.jl
- test/latexify_refs/complex5.txt
This fixes latexify for Complex symbolic values with no imaginary part.
A `Complex` value with no imaginary part `isreal` but is not comparable, but the real part is.
> fix latexify_recipes.jl for real values of type Complex

- src/diff.jl
- src/linearity.jl
- test/diff.jl
I've run into issues similar to https://github.com/JuliaSymbolics/Symbolics.jl/issues/749, https://github.com/JuliaSymbolics/Symbolics.jl/issues/643, https://github.com/JuliaSymbolics/Symbolics.jl/issues/555 etc. with `isaffine`/`islinear`/`hessian_sparsity` repeatedly.
In this PR I propose to assume that functions with unknown linearity are non-linear. This seems to be a safe default that does not report any incorrect structural zeros but would at most error on the other side (missing structural zeros).
Fixes #555.
Fixes #847.
Fixes #790.
Fixes #749.
> Assume unknown functions are non-linear in `hessian_sparsity`

- src/Symbolics.jl
coming from another CAS like sympy the behaviour that expressions are evaluated upon substitution is unexpected. Additionally so far one has to dig one layer down into the symbolicutils documentation to see that this can be solved by a simple kwarg to substitute. This PR adds documentation to said kwarg also in Symbolics.jl.
> document kwarg fold in substitute

- src/diff.jl
- test/diff.jl
This provides a workaround for issues #1126 and #1262 by adding a flag `robust` that if set, forces expand_derivatives to always recalculate `occurrences`.
It also adds tests that check if the examples from the issues are actually solved. These tests also show that `expand_derivatives` can return a wrong result without throwing any error. Line 372 to 375 in `tests/diff.jl`:
```julia
expr = expr_gen(g(y))
@test_broken isequal(expand_derivatives(expr), expand_derivatives(expr; robust=true))
expr = expr_gen(h(y))
@test_broken isequal(expand_derivatives(expr), expand_derivatives(expr; robust=true))
```
I set the robust flag to false per default but since the result of the non-robust version is not reliable it should be considered if setting it to true should be the default.
> add flag for activating robust calculation of expand_derivatives

- src/variable.jl
The old implementation incorrectly warns with "Did not converge after maxiters = 0 substitutions ..." because `maxiters` is decremented, losing its original value in the function call.
> Fix fixpoint_sub warning

- ext/SymbolicsForwardDiffExt.jl
- test/forwarddiff_symbolic_dual_ops.jl
Fixes #1399.
The PR basically copies https://github.com/JuliaDiff/ForwardDiff.jl/pull/717
> Fix ForwardDiff derivative of `NaNMath.pow`

- .github/workflows/ci.yml
- test/runtests.jl
It looks like the tests for the Lux extensions were missed by CI.
> add Lux extension tests in ci

- src/variable.jl
- test/build_function.jl
Requires (and tests) https://github.com/JuliaSymbolics/SymbolicUtils.jl/pull/699
> fix: fix codegen issues in preparation for CSE in MTK

- src/taylor.jl
- test/taylor.jl
Fixes the added test.
`taylor()` calls `substitute()` internally, which uses `fold=true` by defaults, which evaluates numerical expressions, which may not always be desired. These changes allow passing `fold=true` to prevent it.
> Forward taylor expansion keyword arguments to internal substitutions

- src/taylor.jl
- test/taylor.jl
I forgot two `substitute()` calls in https://github.com/JuliaSymbolics/Symbolics.jl/pull/1429...
Sorry for the unnecessary trouble.
> Forward taylor() kwargs to substitute()

- docs/src/manual/arrays.md
As was discussed in #600, there are some useful abstractions for array operations that are already implemented but need to be included in the docs. This PR gives some simple examples of usage to help make the `@arrayop` macro known.
> Add simple examples for @arrayop array operations in docs

- src/Symbolics.jl
- src/utils.jl
- src/variable.jl
- test/utils.jl
I think it is convenient when fiddling around with expressions to easily get numerators/denominators. 
These functions are defined in `Base`, so I think it would be natural to extend them to Symbolics.
> Add numerator, denominator, terms and factors convenience functions

- src/diff.jl
- test/diff.jl
Related to #1453.
Fixes https://github.com/JuliaSymbolics/Symbolics.jl/issues/893
> Fix `hessian_sparsity` for `ifelse`

- src/utils.jl
"Examples" not parsed as a header otherwise
> Add newline in docstring

- .github/workflows/Downstream.yml
- test/downstream/Project.toml
- test/downstream/differentiation_interface.jl
- test/runtests.jl
DI has good tests for symbolic differentiation, so this adds it to our downstream. It also ends up testing FastDifferentiation, but since the entire testset takes ~15 minutes it's not a big deal.
> ci: test DI in downstream CI

- src/arrays.jl
- src/rewrite-helpers.jl
- test/downstream/modeling_toolkit_utils.jl
- test/rewrite_helpers.jl
The problem this is trying to fix is allowing `is_diff_equation` in MTK work for equations like `D(x) ~ p*x`, where `x` is a vector and `p` is an array, not sure if this is the way about it though.
> fix: allow Arr in hasnode

- ext/SymbolicsLuxExt.jl
- test/extensions/lux.jl
I'm trying to make the Lux model in MTKNN a parameter, but we need to call `LuxCore.outputsize` to get the size for symbolic registration. The issue is that in the registered function we get a `SymbolicUtils.BasicSymbolic{<:LuxCore.AbstractLuxLayer}`, but there are not methods that work with that in LuxCore since we need to hit a `AbstractLuxLayer`
```julia
LuxCore.outputsize(layer::AbstractLuxLayer, x, rng::AbstractRNG)
```
We can't register `LuxCore.outputsize` since that would give us a `Num` as a result of the size calculation. Is this a good solution?
> make `outputsize` work with symbolically wrapped lux models

- src/diff.jl
- src/integral.jl
- test/integral.jl
- test/taylor.jl
This PR fixes the following issues when expanding integral differentials:
- derivatives of integral limits are not expanded 
```julia repl
julia> expand_derivatives(Differential(x)(Integral(y in (0, 2a))(u(x,y))))
Integral(y, 0 .. 2a)(Differential(x)(u(x, y))) + u(x, 2a)*Differential(x)(2a)
```
- integral limits are not considered in `occurs_info`
```julia repl
julia> expand_derivatives(Differential(x)(Integral(y in (0, x))(u(y))))
0
```
- shadowing by integration variable of variable against which is derived is not handled. For example $\partial_x \int_0^1 dx u(x) = 0$
```julia repl
expand_derivatives(Differential(x)(Integral(x in (0, 1))(u(x))))
Integral(x, 0 .. 1)(Differential(x)(u(x)))
```
Motivation for this fix is `taylor_coeff` failing for the MWE below. (Well, it doesn't fail …
> fix expansion of integral derivatives

- src/linear_algebra.jl
- src/solver/ia_helpers.jl
- src/solver/ia_main.jl
- src/solver/postprocess.jl
- src/solver/preprocess.jl
for issue #1460 .
in #1445 functions to find numerator and denomniator of expressions were added. I used them to improve code readability of
- `solver/preprocess.jl` `clean_f` function (i tested it with `symbolic_solve(log(x+1)/y, x)`)
- `solver/postprocess.jl` `_postprocess_root` function (i tested it with `symbolic_solve(x*y-1,x)`)
- `solver/ia_main.jl` `isolate` function (i tested it with `symbolic_solve(log(x^2+1)/(y+1)~2/y, x)`)
> Use of the functions numerator and denominator to improve code readability

- src/error_hints.jl
```julia
@variables x, y
x == y ? 0 : 1
```
I can't get rid of the base Julia error hint, so it's just below it.
```julia
ERROR: TypeError: non-boolean (Num) used in boolean context
A symbolic expression appeared in a Boolean context. This error arises in situations where Julia expects a Bool, like
if boolean_condition             use ifelse(boolean_condition, then branch, else branch)
x && y                           use x & y
boolean_condition ? a : b        use ifelse(boolean_condition, a, b)
but a symbolic expression appeared instead of a Bool. For help regarding control flow with symbolic variables, see https://docs.sciml.ai/ModelingToolkit/dev/basics/FAQ/#How-do-I-handle-if-statements-in-my-symbolic-forms?
Symbolic expression found in a control flow expression that …
```
> Error hint when symbolics are used in boolean required control flow

- src/latexify_recipes.jl
Required for https://github.com/SciML/ModelingToolkit.jl/pull/3658
> refactor: make `Equation` latexification more modular

- ext/SymbolicsSymPyExt.jl
- test/sympy.jl
I have fixed the ODE Solver(Test case: 8). This was supposed to be part of #1560 .
The ODE solver test was failing because the code that translates between `Symbolics.jl` and `SymPy.jl` didn't know how to handle derivatives. This caused the math problem to be sent to SymPy in a broken format.
I fixed this by modifying the `symbolics_to_sympy` to correctly convert a Symbolics.jl derivative into a SymPy derivative. I also fixed the code that translates the answer back, making sure it properly handled all the variables involved without mixing up their data types. 
Finally, I updated the test to check the answer in a more reliable way.
Tests are passing locally. It would be great if you could review it, @ChrisRackauckas .
> Fixed ODE Solver(Test case: 8)
